name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore "src/Mavanmanen.StreamDeckSharp/Mavanmanen.StreamDeckSharp.csproj"
    - name: Build
      run: dotnet build --configuration Release --no-restore "src/Mavanmanen.StreamDeckSharp/Mavanmanen.StreamDeckSharp.csproj"
    - name: Test
      run: dotnet test --filter Category!=Integration "src/Mavanmanen.StreamDeckSharp.Test/Mavanmanen.StreamDeckSharp.Test.csproj"
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: "src/Mavanmanen.StreamDeckSharp/Mavanmanen.StreamDeckSharp.csproj"
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
